flexmatch.py:44: UserWarning: You have chosen to seed training. This will turn on the CUDNN deterministic setting, which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
  warnings.warn('You have chosen to seed training. '
Traceback (most recent call last):
  File "flexmatch.py", line 356, in <module>
    main(args)
  File "flexmatch.py", line 66, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/nfs/users/ext_xingping.dong/code/TorchSSL/flexmatch.py", line 95, in main_worker
    world_size=args.world_size, rank=args.rank)
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 436, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 133, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon, timeout)
RuntimeError: Address already in use

flexmatch.py:44: UserWarning: You have chosen to seed training. This will turn on the CUDNN deterministic setting, which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
  warnings.warn('You have chosen to seed training. '
Traceback (most recent call last):
  File "flexmatch.py", line 356, in <module>
    main(args)
  File "flexmatch.py", line 66, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/nfs/users/ext_xingping.dong/code/TorchSSL/flexmatch.py", line 95, in main_worker
    world_size=args.world_size, rank=args.rank)
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 436, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 133, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon, timeout)
RuntimeError: Address already in use

flexmatch.py:44: UserWarning: You have chosen to seed training. This will turn on the CUDNN deterministic setting, which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
  warnings.warn('You have chosen to seed training. '
Traceback (most recent call last):
  File "flexmatch.py", line 356, in <module>
    main(args)
  File "flexmatch.py", line 66, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/nfs/users/ext_xingping.dong/code/TorchSSL/flexmatch.py", line 95, in main_worker
    world_size=args.world_size, rank=args.rank)
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 436, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/nfs/users/ext_xingping.dong/miniconda3/envs/ssl/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 133, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon, timeout)
RuntimeError: Address already in use

